import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import { Header } from '@/components/ui/header'
import { AuthProvider } from '@/providers/auth'
import '../styles/scrollbar.css'
import { getDataUser } from '@/lib/getData/get-data.user'
import PrivateRoute from '@/components/routes-page/private-route'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shopping Store',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { props } = await getDataUser()
  const isAdm = props.isAdm

  return (
    <html lang="en">
      <body className={inter.className}>
        <PrivateRoute isAdm={isAdm}>
          <AuthProvider>
            <Header isAdm={isAdm} />
            {children}
          </AuthProvider>
        </PrivateRoute>
      </body>
    </html>
  )
}
