import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { AuthProvider } from '@/providers/auth'
import '@/styles/scrollbar.css'
import { Header } from '@/components/header'
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import { extractRouterConfig } from 'uploadthing/server'
import Script from 'next/script'
import { UserContextProvider } from '@/providers/user-context'
import { ToastContainer } from 'react-toastify'
import { ourFileRouter } from './api/uploadthing/core'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shopping Store',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></Script>
      <Script src="https://www.mercadopago.com/v1/security.js"></Script>
      <body className={`${inter.className} mx-auto max-w-[1680px]`}>
        <UserContextProvider>
          <AuthProvider>
            <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
            <Header />
            {children}
          </AuthProvider>
        </UserContextProvider>
        <ToastContainer
          autoClose={2000}
          position={'bottom-left'}
          theme="dark"
        />
      </body>
    </html>
  )
}
