name: Run Unit Tests

on: [pull_request, push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_GOOGLE_CLIENT_ID: ${{ secrets.NEXTAUTH_GOOGLE_CLIENT_ID }}
          NEXTAUTH_GOOGLE_CLIENT_SECRET_ID: ${{ secrets.NEXTAUTH_GOOGLE_CLIENT_SECRET_ID }}
          UPLOADTHING_APP_ID: ${{ secrets.UPLOADTHING_APP_ID }}
          UPLOADTHING_SECRET: ${{ secrets.UPLOADTHING_SECRET }}
          JWT_SECRET_KEY_ADM: ${{ secrets.JWT_SECRET_KEY_ADM }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          RUST_BACKTRACE: 1
